set MATLAB=E:\MATLAB
"E:\MATLAB\bin\win64\gmake" -f example.mk  ISPROTECTINGMODEL=NOTPROTECTING GENERATE_ERT_S_FUNCTION=0 INCLUDE_MDL_TERMINATE_FCN=1 COMBINE_OUTPUT_UPDATE_FCNS=0 MAT_FILE=0 MULTI_INSTANCE_CODE=0 INTEGER_CODE=0 EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1 -DTID01EQ=1"
